source/Octopus.Cli/Commands/ApiCommand.cs

Fixes OctopusDeploy/Issues#5625
UserName/Password auth needs to be done before we access Spaces.

User/Pass authentication doesn't work with Octopus Server 2019.1 and up

---

source/Octo.Tests/Octo.Tests.csproj
source/Octopus.Cli/Commands/Package/PushCommand.cs
source/Octopus.Cli/Octopus.Cli.csproj

relates to https://github.com/OctopusDeploy/OctopusClients/pull/431
fixes https://github.com/OctopusDeploy/Issues/issues/5585
```
PS > .\Octo.exe push --server http://localhost:8065 --user admin --pass Sup3rSecrEtPassword! --package fakeservice.1.0.zip --replace-existing
Octopus Deploy Command Line Tool, version 6.7.1-enh-disabledeltapu14
Detected automation environment: "NoneOrUnknown"
Space name unspecified, process will run in the default space context
Handshaking with Octopus Server: http://localhost:8065
Handshake successful. Octopus version: 0.0.0-local; API version: 3.0.0
Authenticated as: admin
Pushing package: fakeservice.1.0.zip...
Requesting signature for delta compression from the server for upload of a package with id 'fakeservice' and version '1.0'
Calculating delta
The …
```

Allow opting out of delta push during package push

---

source/Octopus.Cli/Commands/ExportCommand.cs
source/Octopus.Cli/Commands/ImportCommand.cs

Fixes https://github.com/OctopusDeploy/Issues/issues/5711

Mark the import/export commands as deprecated

---

source/Octo.Tests/Octo.Tests.csproj
source/Octopus.Cli/Commands/Package/BuildInformationCommand.cs
source/Octopus.Cli/Commands/Package/PushMetadataCommand.cs
source/Octopus.Cli/Octopus.Cli.csproj

Relates to OctopusDeploy/Issues#5885

Renaming PackageMetadata to BuildInformation

---

source/Octopus.Cli/Commands/Channel/CreateChannelCommand.cs
source/Octopus.Cli/Commands/Deployment/CreateAutoDeployOverrideCommand.cs
source/Octopus.Cli/Commands/Deployment/DeleteAutoDeployOverrideCommand.cs
source/Octopus.Cli/Commands/Deployment/DumpDeploymentsCommand.cs
source/Octopus.Cli/Commands/Deployment/ListDeploymentsCommand.cs
source/Octopus.Cli/Commands/Deployment/ListLatestDeploymentsCommand.cs
source/Octopus.Cli/Commands/Environment/CleanEnvironmentCommand.cs
source/Octopus.Cli/Commands/Environment/CreateEnvironmentCommand.cs
source/Octopus.Cli/Commands/Environment/ListEnvironmentsCommand.cs
source/Octopus.Cli/Commands/HelpCommand.cs
source/Octopus.Cli/Commands/Machine/ListMachinesCommand.cs
source/Octopus.Cli/Commands/Machine/ListWorkersCommand.cs
source/Octopus.Cli/Commands/Package/PackCommand.cs
source/Octopus.Cli/Commands/Project/CreateProjectCommand.cs
source/Octopus.Cli/Commands/Project/ListProjectsCommand.cs
source/Octopus.Cli/Commands/Releases/DeleteReleasesCommand.cs
source/Octopus.Cli/Commands/Releases/ListReleasesCommand.cs
source/Octopus.Cli/Commands/Tenant/ListTenantsCommand.cs
source/Octopus.Cli/Commands/WorkerPool/CleanWorkerPoolCommand.cs
source/Octopus.Cli/Commands/WorkerPool/CreateWorkerPoolCommand.cs
source/Octopus.Cli/Commands/WorkerPool/ListWorkerPoolsCommand.cs
source/Octopus.Cli/Exporters/ProjectExporter.cs
source/Octopus.Cli/Exporters/ReleaseExporter.cs
source/Octopus.Cli/Importers/ProjectImporter.cs
source/Octopus.Cli/Importers/ReleaseImporter.cs

Add full stops to the end of all descriptions

Ensure consistency in command descriptions

---

source/Octopus.Cli/Commands/Deployment/CreateAutoDeployOverrideCommand.cs
source/Octopus.Cli/Commands/Deployment/DeleteAutoDeployOverrideCommand.cs
source/Octopus.Cli/Commands/Deployment/ListDeploymentsCommand.cs
source/Octopus.Cli/Commands/Deployment/ListLatestDeploymentsCommand.cs
source/Octopus.Cli/Commands/Environment/ListEnvironmentsCommand.cs
source/Octopus.Cli/Commands/Releases/AllowReleaseProgressionCommand.cs
source/Octopus.Cli/Commands/Releases/ListReleasesCommand.cs
source/Octopus.Cli/Commands/Releases/PreventReleaseProgressionCommand.cs
source/Octopus.Cli/Commands/Tenant/ListTenantsCommand.cs
source/Octopus.Cli/Commands/VersionCommand.cs
source/Octopus.Cli/Commands/WorkerPool/ListWorkerPoolsCommand.cs

**Context**
There are quite a few command descriptions start with a verb not in the third person singular form whereas other command descriptions start with a verb in the third person singular form. Please refer to the below screenshot.
**Screenshot(s)**
**Content**
Updated command description for consistency

Update command description for consistency

---

BuildAssets/repos/test-linux-package-from-feed-in-dists.sh
BuildAssets/test-linux-package-in-dists.sh

This change applies a security improvement from OctopusDeploy/OctopusTentacle#201.

Restrict sensitive RedHat variables to RedHat containers

---

source/Octopus.DotNet.Cli/Octopus.DotNet.Cli.csproj

Tested using:
```
./build.sh --target Build
```

Add dotnet 5.0 target

---

source/Octopus.Cli/Commands/Package/BuildInformationCommand.cs

The check was being done in a way that wasn't compatible with the default space being disabled.
This check was put in place to address forward and backward compatible back when the PackageMetadata API was renamed to BuildInformation (in 2019). The PackageMetadata API has been deprecated since then and has actually been removed in `2021.2`, so the fallback is no longer required or valid, and has been removed.
Fixes #118

Removed the feature check for BuildInformation

---

source/Octopus.Cli/Commands/Runbooks/RunRunbookCommand.cs

Adding changes to help as suggested by @donnybell here -> https://github.com/OctopusDeploy/docs/pull/1301/files

Suggested changes to run-runbook command options

---

source/Octopus.Cli/Commands/Releases/CreateReleaseCommand.cs

packagePrerelease also supports regex patterns

Added extra doco to command line argument

---

source/Octopus.Cli/Commands/Deployment/DeploymentCommandBase.cs

This can cause System.IndexOutOfRangeException: Index was outside the bounds of the array.
Fixes https://github.com/OctopusDeploy/OctopusClients/issues/355

List being updated by multiple threads

---

source/Octo.Tests/Octo.Tests.csproj
source/Octopus.Cli/Commands/Releases/CreateReleaseCommand.cs
source/Octopus.Cli/Octopus.Cli.csproj
source/Octopus.Cli/Util/RepositoryExtensions.cs

The client has been updated to identify the GitHub Actions automation environment correctly.

Update client for new deployment automation understanding

---

.nuke/build.schema.json
build.cmd
build.ps1
build/Build.cs
build/_build.csproj

We need to do this because we are now running builds in docker containers

Making sure we are authenticated to docker registry before push

---

source/Octo.Tests/Commands/ListReleasesCommandFixture.cs
source/Octo.Tests/Commands/ReleasePlanBuilderTests.cs
source/Octo.Tests/Octo.Tests.csproj
source/Octopus.Cli/Commands/Releases/CreateReleaseCommand.cs
source/Octopus.Cli/Commands/Releases/ReleasePlanBuilder.cs
source/Octopus.Cli/Octopus.Cli.csproj

This also covers the changes in: https://github.com/OctopusDeploy/OctopusCLI/pull/155

Update to latest Octopus.Server.Client and Server.MessageContracts

---

source/Octopus.Cli/Commands/Releases/CreateReleaseCommand.cs

Throw if `CreateRelease` command is missing gitref

---

source/Octo/Octo.csproj
source/Octopus.Cli/Octopus.Cli.csproj
source/Octopus.DotNet.Cli/Octopus.DotNet.Cli.csproj

Fixes https://github.com/OctopusDeploy/OctopusCLI/issues/172

Remove net5 targets

---

source/Octo.Tests/Commands/ReleasePlanBuilderTests.cs
source/Octopus.Cli/Commands/Releases/ReleasePlanBuilder.cs

This reverts commit 324db463ae7e9fbae23b08f05ba837b5ea967722.

Revert "Always use ID when fetching feeds"

---

.github/workflows/build.yml
.github/workflows/release.yml
.octopus/deployment_process.ocl
.octopus/deployment_settings.ocl
.octopus/schema_version.ocl

We've adjusted which user is doing the update to the homebrew-taps repo, to handle issues with branch protection rules.

Fix homebrew publish

---

source/Octo.Tests/Octo.Tests.csproj

We'll be using this PR to test our new `homebrew-taps` update process

fix: update dependencies

---

source/Octo.Tests/Commands/CreateReleaseCommandFixture.cs
source/Octopus.Cli/Commands/Releases/CreateReleaseCommand.cs

Validate that the release version passed does not contain whitespace

---

.github/workflows/build.yml
source/Octo.Tests/Commands/CreateReleaseCommandFixture.cs
source/Octopus.Cli/Commands/Releases/CreateReleaseCommand.cs

Fixes a regression from an earlier PR.
Fixes #238

Corrected null reference exception when release version wasn't specified

---

.github/workflows/build.yml
BuildAssets/test-linux-package.sh
build/Build.cs

Also removed use of `set-output` in actions

removed oldoldstable-slim from testing matrix
