source/Octopus.Cli/Commands/Deployment/TaskOutputProgressPrinter.cs

Before:
```
Creating release...
Release 1.0.18 created successfully!
##teamcity[setParameter name='octo.releaseNumber' value='1.0.18']
Deploying TeamCity Service Message test "1.0.18" to: Dev (Guided Failure: Not Enabled)
Waiting for 1 deployment(s) to complete....
##teamcity[blockOpened name='Success: Acquire packages']
##teamcity[message text='Acquiring packages' status='NORMAL']
##teamcity[message text='Making a list of packages to acquire' status='NORMAL']
##teamcity[message text='All packages have been acquired' status='NORMAL']
##teamcity[blockOpened name='Success: Octopus Server']
##teamcity[blockOpened name='Success: Download package MyScript v1.0.1 from Octopus Server (built-in)']
##teamcity[message text='Package MyScript v1.0.1 was found in cache. No need to download from feed.' …
```

If log entry line is a TeamCity service message, output line as-is. 

---

source/Octo.Tests/Octo.Tests.csproj
source/Octopus.Cli/Commands/Package/PushCommand.cs
source/Octopus.Cli/Commands/Package/PushMetadataCommand.cs
source/Octopus.Cli/Octopus.Cli.csproj

Adding `--overwrite-mode`, to replace the `--replace-existing` flag. Adds the ability for the caller to IgnoreExisting.
Relates to OctopusDeploy/Octopus-TeamCity#18

Added overwrite-mode to the push and push metadata commands

---

source/Octo.Tests/Commands/ApiCommandFixture.cs
source/Octo.Tests/Commands/ApiCommandFixtureBase.cs
source/Octo.Tests/Commands/CreateReleaseCommandFixture.cs
source/Octo.Tests/Commands/DeployReleaseCommandTestFixture.cs
source/Octopus.Cli/Commands/ApiCommand.cs
source/Octopus.Cli/Commands/Deployment/DeployReleaseCommand.cs
source/Octopus.Cli/Commands/Deployment/DeploymentCommandBase.cs
source/Octopus.Cli/Commands/Package/PushMetadataCommand.cs
source/Octopus.Cli/Commands/Releases/CreateReleaseCommand.cs
source/Octopus.Cli/Commands/Releases/DeleteReleasesCommand.cs
source/Octopus.Cli/Commands/Releases/PromoteReleaseCommand.cs
source/Octopus.Cli/Importers/ProjectImporter.cs
source/Octopus.Cli/Infrastructure/CouldNotFindException.cs
source/Octopus.Cli/Octopus.Cli.csproj
source/Octopus.Cli/Util/RepositoryExtensions.cs
source/OctopusCli.sln.DotSettings

Allows IDs to be used in place of names in all arguments to `push`, `create-release`, `deploy-release`, and `promote-release`.
* Only fetches IDs if they are in the right format.
* API calls include the `?name=...` query to minimize slurping of full pages.
* Aborts if somebody is unlucky enough to hit a name/ID ambiguity.
* Introduces repository extension methods for consistency, with logging & error messages slightly more detailed than before.
* Adds specific assertions to some tests that were passing in situations where they shouldn't.

Accept IDs in arguments to push, create-release, deploy-release, promote-release

---

source/Octo.Tests/Octo.Tests.csproj
source/Octopus.Cli/Commands/Package/PushMetadataCommand.cs
source/Octopus.Cli/Octopus.Cli.csproj

Updates OctopusClients to get nicer check for push-metadata support on Octopus Server.
```
PS > .\octo.exe push-metadata --server=htps://octopus.example.com --apikey API-XXXXXXX --metadata-file foo.txt --package-id foo --version "1.2.3"                                                                                                                                                                                                               Detected automation environment: "NoneOrUnknown"
Process will run in backwards compatible mode for older versions of Octopus Server
Handshaking with Octopus Server: https://octopus.example.com
Handshake successful. Octopus version: 2018.10.1; API version: 3.0.0
Authenticated as: admin
Pushing package metadata: "foo"...
Pushing build information/package …
```

Metadata push validation

---

source/Octo.Tests/Commands/PackageVersionResolverNamedPackagesFixture.cs
source/Octopus.Cli/Commands/Releases/CreateReleaseCommand.cs
source/Octopus.Cli/Commands/Releases/IPackageVersionResolver.cs
source/Octopus.Cli/Commands/Releases/PackageVersionResolver.cs

The command line currently interprets something like `StepA:1.0.0` to mean a package reference name of blank string, which means it will only match the default package and not any of the named package references. 
This is not at all intuitive when dealing with something like `PackageA:1.0.0`, which feels like "whichever step PackageA appears in, use version 1.0.0". The wildcard not also spanning package reference names then feels unexpected.
This PR changes the default behaviour to assume WildCard rather than "default package reference name".
Fixes OctopusDeploy/Issues#5821

Changed the default package wildcard behavior for `create-release`

---

source/Octo.Tests/Commands/ApiCommandFixture.cs
source/Octopus.Cli/Commands/ApiCommand.cs

Fixes https://github.com/OctopusDeploy/OctopusCLI/issues/22
```
PS > .\Octo.exe push --server $server --apikey $apikey --package C:\temp\fakeservice.1.0.zip --overwrite-mode overwriteexisting
Octopus Deploy Command Line Tool, version 1.0.0
Detected automation environment: "NoneOrUnknown"
Space name unspecified, process will run in the default space context
Handshaking with Octopus Server: http://localhost:8065
Handshake successful. Octopus version: 0.0.0-local; API version: 3.0.0
Authenticated as: admin
Pushing package: C:\temp\fakeservice.1.0.zip...
Requesting signature for delta compression from the server for upload of a package with id 'fakeservice' and version '1.0'
Calculating delta
The delta file (59 bytes) is 0.00% the size of the orginal file (1,575,824 bytes), uploading...
Delta …
```

Add parameter validation for --timeout and --keepalive

---

source/Octo/runtimeconfig.template.json

@jeremyabbott contributed a PR to enable compatibility with .NET Core Runtime 3. This is a good idea, but I noticed the option is deprecated. I think we'll proceed with the new option: `"rollForward": "Major"`
I've tested this on an Azure DevOps build pipeline with only .NET Core 3.0 installed.
The original PR: https://github.com/OctopusDeploy/OctopusCLI/pull/25

Allow roll forward to newer major framework versions

---

source/Octopus.Cli/Commands/Package/PushMetadataCommand.cs

So that our docs get updated to highlight its out of date.

Update help for push-metadata to flag as deprecated.

---

source/Octo.Tests/Octo.Tests.csproj
source/Octo/Octo.csproj
source/Octopus.Cli/Octopus.Cli.csproj

In this PR, the net framework target frameworks are disabled if the environment is not a windows environment. This prevents unnecessary IDE errors on these environments.

Improve development experience on non-windows environments

---

BuildAssets/Octo

This prevents changing to the `Octo` path, which is a surprise when trying to do an operation like `Octo pack` and the `Octo` path is packed instead of the current path.

Launch Octo from absolute path

---

Dockerfiles/alpine/Dockerfile
Dockerfiles/nanoserver/Dockerfile
build.cake
source/Octo/Octo.csproj
source/Octopus.DotNet.Cli/Octopus.DotNet.Cli.csproj

Upgrading everything to 3.1 immediately was going to cause compatibility problems:
- The portable .NET Core Zip and `dotnet tool install Octopus.DotNet.Cli` would require .NET Core runtime 3.1 instead of 2.0, without sufficient warning
- OctoTFS would also fall victim to this
- The Windows nanoserver docker image currently depends on a `sac2016` base image that is no longer being shipped for new .NET Core versions, so would have needed rework
This change multitargets the `octo` and `Octopus.DotNet.Cli` projects, so that:
- `octo` targets .NET Core 3.1 for the self-contained executables
- `octo` continues to target .NET Core 2.0 for the portable .NET Core zip
- `Octopus.DotNet.Cli` nuget package contains binaries for both 2.1 and 3.1, and the tool installer picks the right one
- Windows …

Multitarget octo & dotnet tool for continuity with past releases - portable zip targets 2.0 again

---

source/Octo.Tests/Commands/HelpCommandFixture.cs
source/Octopus.Cli/Commands/CommandBase.cs

Was showing as `Octopus.Cli`. Should show as `octo`

Fix up the executable name in the help

---

BuildAssets/Octo
BuildAssets/Octo.cmd
BuildAssets/OctopusTools.nuspec
BuildAssets/octo.cmd
Dockerfiles/Readme.md
Dockerfiles/alpine/Dockerfile
Dockerfiles/nanoserver/Dockerfile
build.cake
readme.md
source/Octo.Tests/Commands/HelpCommandFixture.cs
source/Octo.Tests/Octo.Tests.csproj
source/Octo/Octo.csproj
source/Octopus.Cli/CliProgram.cs
source/Octopus.Cli/Commands/ApiCommand.cs
source/Octopus.Cli/Commands/ExportCommand.cs
source/Octopus.Cli/Commands/HelpCommand.cs
source/Octopus.Cli/Commands/ImportCommand.cs
source/Octopus.Cli/Commands/VersionCommand.cs
source/Octopus.Cli/Util/AssemblyExtensions.cs
source/Octopus.Cli/Util/FeatureDetectionExtensions.cs
source/Octopus.DotNet.Cli/Octopus.DotNet.Cli.csproj
tools/packages.config

We have reclassified the impact of these changes as a major bump, so we want to revert them to finish the 6.17.x release series before applying them again.
This reverts changes relating to lowercase, .NET Core 3.1, and self-contained.

Revert changes relating to lowercase, .NET Core 3.1, and self-contained

---

build.cake

The Chocolatey package, and nuget's OctousTools package, currently contain a .NET Framework Windows executable.
This uses the .NET Core 3.1 self-contained windows x64 executable in those packages instead.

OctopusTools package: switch from netfx-merged to self-contained win-x64

---

source/Octo.Tests/Commands/ApiCommandFixtureBase.cs
source/Octo.Tests/Commands/DummyApiCommand.cs
source/Octo.Tests/Commands/SupportFormattedOutputFixture.cs
source/Octo.Tests/Helpers/ConsoleWriter.cs
source/Octopus.Cli/Commands/CommandBase.cs
source/Octopus.Cli/Util/CommandOutputProvider.cs
source/Octopus.Cli/Util/ICommandOutputProvider.cs

Adds the help description to the top of the `--help` output
(this was an old bit of code that I had around but never quite got around to finishing.)
```
PS> octo version --help
Usage: octo version [<options>]
Where [<options>] is any of:
Common options:
--help                 [Optional] Print help for a command
--helpOutputFormat=VALUE
[Optional] Output format for help, only valid
option is json
```
```
PS> octo version --help
Output Octopus CLI version.
Usage: octo version [<options>]
Where [<options>] is any of:
Common options:
--help                 [Optional] Print help for a command
--helpOutputFormat=VALUE
[Optional] Output format for help, only valid
option is json
```
note the extra `Output Octopus CLI version.` at the top

Include the help description in the help output

---

BuildAssets/OctoWrapper.sh
BuildAssets/octo
build.cake

Before 7.0.0, the `octo` command was capitalized: `Octo`.
The change doesn't affect invocations in Windows or macOS, but it does affect linux.
This change adds capitalized `Octo` wrappers to the Linux and portable tarballs. We haven't put these in the Windows / macOS / portable `.zip` archives, because having `Octo` and `octo` in the same archive has confusing effects on case-insensitive systems like Windows and macOS.

Add capitalized Octo wrapper to tar.gz for linux & portable

---

Dockerfiles/Readme.md
Dockerfiles/alpine/Dockerfile
Dockerfiles/nanoserver/Dockerfile
build.cake
source/OctopusCli.sln

So that we can:
* find issues earlier
* (eventually) run tests when we build the container
* have a quicker publish
* stop deploy.octopushq.com doing build stuff

Build docker images during build phase, not publish phase

---

BuildAssets/create-linux-packages.sh

This change adds to the `.deb` and `.rpm` packages:
- Declares the dependencies listed [by Microsoft](https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-linux#supported-operating-systems), adjusted to suit:
- the last ~5 years of Debian & Ubuntu
- the latest Linux Mint
- CentOS 7-8
- Fedora latest
- Add executable permission, which was in our dependency `.tar.gz`, but TeamCity didn't seem to be preserving when it unzipped
- Add a symlink to `octo` in `/usr/bin/` so that it will be on the `$PATH`.
Basic smoke tests (for now checking only exit code of `octo version`) for 4 distros are [on TeamCity](https://build.octopushq.com/viewType.html?buildTypeId=OctopusDeploy_OctopusCLI_TestLinuxPackages&branch_OctopusDeploy_OctopusCLI=enh-pkg-symlink-deps&tab=bu …

Linux packages: add dependencies, executable permission, symlink

---

BuildAssets/repos/publish-apt.sh
BuildAssets/repos/publish-rpm.sh
BuildAssets/repos/test-apt.sh
BuildAssets/repos/test-rpm.sh
BuildAssets/test-linux-packages.sh
build.cake

This adds scripts to the archive with our linux packages that are used in the build and deploy:
- `test-linux-packages.sh` tests the `deb` and `rpm` packages in a variety of dockerized distros, to ensure `octo version` and `octo list-environments` work
- `publish-apt.sh` - creates a local repo based on our S3 repo, publishes our `deb`, pushes it back
- `publish-rpm.sh` - syncs the S3 repo to local, publishes our `rpm`, syncs back to S3
- `test-apt.sh` - tests the `apt` repo to ensure `octo version` and `octo list-environments` work
- `test-rpm.sh` - tests the `rpm` repo with yum to ensure `octo version` and `octo list-environments` work
Please review the contents of the scripts.

Test deb/rpm packages and publish them to apt/yum repos

---

source/Octopus.DotNet.Cli/Octopus.DotNet.Cli.csproj

We thought we'd fixed this in https://github.com/OctopusDeploy/OctopusCLI/pull/25, but it didn't have the desired outcome.
While we are now encouraging customers to use platform native executables (available from the [downloads page](https://octopus.com/downloads/octopuscli)), this fixes it so that it works again.
Fixes https://github.com/OctopusDeploy/OctopusCLI/issues/28

Support netcore 2.1, 2.2, 3.0 and 3.1 for dotnet tool

---

source/Octo/Octo.csproj
source/Octopus.Cli/CliProgram.cs
source/Octopus.Cli/Octopus.Cli.csproj

We had all the code, but the compile time constant was in the wrong project.
This also needed us to upgrade past netcoreapp2.0.
Fixes https://github.com/OctopusDeploy/Issues/issues/4948
Fixes https://github.com/OctopusDeploy/Issues/issues/5906

Fix up --ignoreSslErrors on linux

---

BuildAssets/create-linux-packages.sh
BuildAssets/repos/README.md
BuildAssets/repos/publish-apt.sh
BuildAssets/repos/publish-rpm.sh
BuildAssets/repos/test-apt-dists.sh
BuildAssets/repos/test-apt.sh
BuildAssets/repos/test-rpm-dists.sh
BuildAssets/repos/test-rpm.sh
BuildAssets/test-linux-packages.sh
build.cake

Our existing process involves pulling everything down from S3, adding the new Octopus CLI or Tentacle package, regenerating the apt & yum feeds, and pushing back to S3.
It currently has some drawbacks:
- Quite slow & fragile
- Leaves open a wide window when Tentacle and Octopus CLI processes could come into conflict, as well as tension over which project "owns" the repos
- Yum repos are not signed
- The distribution specifier for apt is always `stretch`, which is overly specific and out of date
This change treats Artifactory as the owner of the feed state, with S3 as a backup. There is a safeguard included so we don't push to S3 from Artifactory if doing so would remove packages. If/when we actually want to remove a package, we will remove from both Artifactory and S3 to confirm that.
Yum …

Assemble apt & yum feeds in Artifactory before pushing to S3

---

source/Octo.Tests/Commands/OverrideAutoDeployCommandFixture.cs
source/Octopus.Cli/Commands/ApiCommand.cs
source/Octopus.Cli/Commands/Deployment/CreateAutoDeployOverrideCommand.cs
source/Octopus.Cli/Commands/Deployment/DeleteAutoDeployOverrideCommand.cs
source/Octopus.Cli/Commands/Deployment/DeployReleaseCommand.cs
source/Octopus.Cli/Commands/Deployment/DeploymentCommandBase.cs
source/Octopus.Cli/Commands/Environment/CleanEnvironmentCommand.cs
source/Octopus.Cli/Commands/InstallAutoCompleteCommand.cs
source/Octopus.Cli/Commands/Machine/ListMachinesCommand.cs
source/Octopus.Cli/Commands/Machine/ListWorkersCommand.cs
source/Octopus.Cli/Commands/Package/PackCommand.cs
source/Octopus.Cli/Commands/Releases/CreateReleaseCommand.cs
source/Octopus.Cli/Commands/Releases/DeleteReleasesCommand.cs
source/Octopus.Cli/Commands/Releases/PromoteReleaseCommand.cs
source/Octopus.Cli/Commands/WorkerPool/CleanWorkerPoolCommand.cs
source/Octopus.Cli/Diagnostics/LogExtensions.cs
source/Octopus.Cli/Repositories/OctopusRepositoryCommonQueries.cs

Part of the work to auto-generate the specification required for nuke build.
See https://github.com/nuke-build/nuke/blob/develop/build/specifications/Octopus.json

Made all the command options use camelCase for consistency

---

source/Octo.Tests/Commands/CompleteCommandFixture.cs
source/Octo.Tests/Commands/InstallAutoCompleteFixture.cs
source/Octo.Tests/Commands/SpeakCommand.cs
source/Octopus.Cli/Commands/ApiCommand.cs
source/Octopus.Cli/Commands/CommandBase.cs
source/Octopus.Cli/Commands/CompleteCommand.cs
source/Octopus.Cli/Commands/HelpCommand.cs
source/Octopus.Cli/Commands/InstallAutoCompleteCommand.cs
source/Octopus.Cli/Commands/Package/PackCommand.cs
source/Octopus.Cli/Commands/VersionCommand.cs

This is used for auto-generation of docs
Fixes #63
```
PS > .\octo.exe --install-autocomplete --help
Please specify the type of shell to install auto-completion for: --shell=XYZ. Valid values are Pwsh, Zsh, Bash and Powershell.
Exit code: -1
```
```
PS > .\octo.exe complete --help
--help
--helpOutputFormat
```
```
PS > .\octo.exe --install-autocomplete --help
Install a shell auto-complete script into your shell profile, if they aren't already there. Supports pwsh, zsh, bash & powershell.
Usage: octo install-autocomplete [<options>]
Where [<options>] is any of:
Install AutoComplete:
--shell=VALUE          The type of shell to install auto-complete
scripts for. This will alter your shell
configuration files. Supported shells are Pwsh,
Zsh, Bash and Powershell.
--dryRun …
```

Make `install-autocomplete` and `complete` support `--help` argument

---

source/Octopus.Cli/Commands/ApiCommand.cs

Corrected the typo "your must" to "you must". This appears in multiple places in the docs via the CLI docs generator and the CLI itself.

Corrected a typo

---

BuildAssets/create-linux-packages.sh
BuildAssets/repos/publish-apt.sh

This includes two changes to make Octopus CLI install properly in the new LTS ubuntu focal:
- Adds the `libicu` dependency with the new version number for focal
- Adds 'focal' as one of the dist specifiers we support

Add support for ubuntu focal, new LTS

---

BuildAssets/repos/test-apt.sh

Because the primary purpose of this script is to test Octopus CLI, we can test that separately, and first.
The quick tentacle smoke test is a secondary thing that is currently not supported yet on ubuntu focal, so this change also makes that a soft failure for now. I think it's still useful to leave in the process for diagnostic reasons.

Test tentacle separately, with soft failure for now

---

source/Octo.Tests/Octo.Tests.csproj
source/Octopus.Cli/Commands/Runbooks/RunRunbookCommand.cs
source/Octopus.Cli/Octopus.Cli.csproj

Bumps the OctopusClient version 8.8.0->8.8.1
Client update is to facilitate server version checking for backward compatibility of this too with previous API endpoints.

Bumps client version to 8.8.1

---

BuildAssets/create-octopuscli-linux-packages.sh
BuildAssets/repos/test-linux-package-from-feed-in-dists.sh
BuildAssets/repos/test-linux-package-from-feed.sh
BuildAssets/test-linux-package-in-dists.sh
BuildAssets/test-linux-package.sh
build.cake

This branch includes 6 unrelated minor improvements, mostly defensive coding and expanding upon explanations (after review discussions on OctopusDeploy/OctopusTentacle#201).
It will be easiest to look over each individual commit:
- Remove unused variable
- Increase test hostname specificity
- Add exit code check (no impact, just for convention / defensiveness)
- Fail if the Tentacle test fails, because it's worth being aware of
- Expand error messages to explain where to get linux-package-feeds
- Clarify the purpose of calls out to linux-package-feeds scripts

Minor packaging improvements

---

build.cake

This passes environment variables SIGN_PRIVATE_KEY and SIGN_PASSPHRASE from the outside environment (usually TeamCity) through to the package creation process, to support OctopusDeploy/linux-package-feeds#1.

Pass signing secrets through into the package creation process

---

source/Octopus.Cli/Commands/Runbooks/RunRunbookCommand.cs

Previously we only allowed tenants to be discovered via ID. This change allows name or id to be used.

Runbook Command: lookup tenant by Id or name

---

BuildAssets/repos/test-linux-package-from-feed.sh

The Octopus CLI linux package deployment process includes a secondary smoke check to confirm we haven't just broken Tentacle, which shares the same APT and RPM repos.
We had a workaround in place to skip that check on Ubuntu `focal`, as Tentacle had not shipped with its dist specifier yet.
Now that Tentacle is shipped specifically with the `focal` dist specifier, the workaround can go away.

Remove compatibility check now that tentacle is available with focal sources

---

source/Octo.Tests/Commands/ReleasePlanBuilderTests.cs
source/Octo.Tests/Octo.Tests.csproj
source/Octopus.Cli/Commands/Releases/CreateReleaseCommand.cs
source/Octopus.Cli/Commands/Releases/IReleasePlanBuilder.cs
source/Octopus.Cli/Commands/Releases/ReleasePlanBuilder.cs
source/Octopus.Cli/Octopus.Cli.csproj

This PR adds the `--gitRef` parameter to the `create-release` command to enable creating release for version controlled projects from a git reference.
Example usage:
`create-release --server http://localhost:8065 --project  "Config as Code" --gitRef main`
Sample output:
```
Detected automation environment: "NoneOrUnknown"
Handshaking with Octopus Server: http://localhost:8065
Handshake successful. Octopus version: 0.0.0-local; API version: 3.0.0
Authenticated as: admin
Found environments:
This Octopus Server supports channels
Found project: Config as Code (Projects-201)
Automatically selecting the best channel for this release...
Building a release plan for Channel 'Default'...
Finding deployment process at git reference main...
Finding release template at git reference main...
Selected …
```

Create release from git reference

---

source/Octo.Tests/Commands/ListReleasesCommandFixture.JsonFormat_ShouldBeWellFormed.approved.txt
source/Octo.Tests/Commands/ListReleasesCommandFixture.ShouldGetListOfReleases.approved.txt
source/Octo.Tests/Commands/ListReleasesCommandFixture.cs
source/Octo.Tests/Helpers/ApprovalScrubberExtensions.cs
source/Octo.Tests/Octo.Tests.csproj
source/Octopus.Cli/Commands/ApiCommand.cs
source/Octopus.Cli/Commands/Releases/ListReleasesCommand.cs

This PR adds the reference and commit to `list-releases` output for version controlled projects:
```
- Project: Version controlled project
Version: 1.2.3
Assembled: <ASSEMBLED-TIMESTAMP>
Package Versions: 
Release Notes: Version controlled release notes
Git Reference: main
Git Commit: 87a072ad2b4a2e9bf2d7ff84d8636a032786394d
```

Show git commit and reference when listing releases

---

source/Octo.Tests/Commands/ReleasePlanBuilderTests.cs
source/Octopus.Cli/Commands/Releases/ChannelVersionRuleTester.cs
source/Octopus.Cli/Commands/Releases/IChannelVersionRuleTester.cs
source/Octopus.Cli/Commands/Releases/ReleasePlanBuilder.cs

The `/channels/rule-test` endpoint can accept a feed ID (https://github.com/OctopusDeploy/OctopusDeploy/blob/ffcc26ebf15a444ed25633073ac41d45bb99f0d2/source/Octopus.Server/Web/Api/Actions/VersionRuleTestAction.cs#L58) which it uses to build the package version to check against the version range. This change sends the feed id to the endpoint to ensure the package version is correctly generated.

Pass feed id when verifying channel rules

---

source/Octo.Tests/Commands/ReleasePlanBuilderTests.cs
source/Octopus.Cli/Commands/Releases/ReleasePlanBuilder.cs

Feeds in a deployment processes may be referenced by name or id depending on whether the project is version controlled or not. This PR looks up feeds by the appropriate key when creating a release.

Handle feed names in deployment process for cac projects

---

build.cake
source/Octo.Tests/Commands/AllowReleaseProgressionCommandFixture.cs
source/Octo.Tests/Commands/DeployReleaseCommandTestFixture.cs
source/Octo.Tests/Commands/ListDeploymentsCommandFixture.cs
source/Octo.Tests/Commands/ListLatestDeploymentsCommandFixture.cs
source/Octo.Tests/Commands/ListReleasesCommandFixture.JsonFormat_ShouldBeWellFormed.approved.txt
source/Octo.Tests/Commands/ListReleasesCommandFixture.ShouldGetListOfReleases.approved.txt
source/Octo.Tests/Commands/ListReleasesCommandFixture.cs
source/Octo.Tests/Commands/OverrideAutoDeployCommandFixture.cs
source/Octo.Tests/Commands/PackageVersionResolverFixture.cs
source/Octo.Tests/Commands/PackageVersionResolverNamedPackagesFixture.cs
source/Octo.Tests/Commands/PreventReleaseProgressionCommandFixture.cs
source/Octo.Tests/Commands/ReleasePlanBuilderTests.cs
source/Octo/Octo.csproj
source/Octopus.Cli/Commands/Releases/AllowReleaseProgressionCommand.cs
source/Octopus.Cli/Commands/Releases/DeleteReleasesCommand.cs
source/Octopus.Cli/Commands/Releases/PackageVersionResolver.cs
source/Octopus.Cli/Commands/Releases/PreventReleaseProgressionCommand.cs
source/Octopus.Cli/Commands/Releases/PromoteReleaseCommand.cs
source/Octopus.Cli/Commands/Releases/ReleasePlan.cs
source/Octopus.Cli/Exporters/ReleaseExporter.cs
source/Octopus.Cli/Octopus.Cli.csproj
source/Octopus.Cli/Repositories/OctopusRepositoryCommonQueries.cs

This PR parses release versions as Octopus versions instead of semver to support Docker versioning.

Allow new release versions in CLI commands

---

.nuke
.nuke/build.schema.json
.nuke/parameters.json
build.ps1
build.sh
build/Build.cs
build/_build.csproj
global.json

We [upgraded](https://github.com/OctopusDeploy/tool-containers/pull/25) the base build image to install the latest nuke.globaltool (version 5.1.0).
Nuke 5.1.0 [includes a new version](https://github.com/nuke-build/nuke/commit/bef28aab33d202688f67f527f7692b360ba93fa4) of GitVersion.Tool.
This meant we [had to update](https://github.com/OctopusDeploy/tool-containers/pull/25/files#diff-3dc3767944d5097e69dbc20d45548730bb43dfdbde1be7edfdb4140a66c6cfa1R58) the path (LD_LIBRARY_PATH) to the new native tool binaries.
Unfortunately this meant that while new stuff will build, old stuff will not.
As a quick fix, we are updating all projects to nuke 5.1.0 while we ponder the proper fix.
This should have no impact to the builds - if any, it'll be to take it from broken to 💚

Upgrade to nuke 5.1.0

---

BuildAssets/test-linux-package-in-dists.sh
BuildAssets/test-linux-package.sh
source/OctopusCli.sln

We started getting issues in our tests from the 29th of April:
```
07:13:10  == Testing in 'fedora:latest' ==
07:12:41  Installing package.
07:13:10  
07:13:10  Installed:
07:13:10    libicu-67.1-6.fc34.x86_64             octopuscli-7.4.3199-1.x86_64
07:13:10  
07:13:10  Testing octo.
07:13:10  realpath(): Operation not permitted
07:13:10  realpath(): Operation not permitted
07:13:10  Failure processing application bundle.
07:13:10  Failed to determine location for extracting embedded files
07:13:10  DOTNET_BUNDLE_EXTRACT_BASE_DIR is not set, and a read-write temp-directory couldn't be created.
07:13:10  A fatal error was encountered. Could not extract contents of the bundle
07:13:11  Process exited with code 159
```
Seems related to https://github.com/dotnet/runtime/issues/47535.
Setting …

Fix tests in fedora:latest

---

Dockerfiles/alpine/Dockerfile
Dockerfiles/nanoserver/Dockerfile
build/Build.cs

Base image has also changed from `microsoft/dotnet:2.1-runtime-nanoserver-sac2016` to `mcr.microsoft.com/dotnet/runtime:3.1-nanoserver-20H2`, as the old one is being removed, and only newer ones are available.
The dockerfile had to change too, as powershell is no longer installed on the base image.

Docker base images have moved to mcr.microsoft.com

---

.nuke/build.schema.json
build/Build.cs
build/_build.csproj

So that the cert is loaded from azure key vault rather than disk
outstanding tasks:

Use AzureSignTool for code signing

---

source/Octo.Tests/Commands/ReleasePlanBuilderTests.cs
source/Octo.Tests/Octo.Tests.csproj
source/Octopus.Cli/Commands/Releases/CreateReleaseCommand.cs
source/Octopus.Cli/Commands/Releases/IReleasePlanBuilder.cs
source/Octopus.Cli/Commands/Releases/ReleasePlanBuilder.cs
source/Octopus.Cli/Importers/ProjectImporter.cs
source/Octopus.Cli/Octopus.Cli.csproj
source/Octopus.Cli/Util/FeatureDetectionExtensions.cs

Added support for `--gitCommit` parameter 
**Release with `--gitCommit` (note `--gitRef` is still required)**
> Octopus Deploy Command Line Tool, version 1.0.0
> 
> Detected automation environment: "NoneOrUnknown"
> Space name unspecified, process will run in the default space context
> Handshaking with Octopus Server: http://localhost:8065
> Handshake successful. Octopus version: 0.0.0-local; API version: 3.0.0
> Authenticated as: admin
> Found environments:
> This Octopus Server supports channels
> Found project: Simple Project (Projects-1)
> Automatically selecting the best channel for this release...
> Building a release plan for Channel 'Default'...
> Finding deployment process at git commit c5cb0388ce999b64308bb2abd0db705832ff2afb...
> Finding release template at git commit …

Support passing a specific release when creating a commit

---

BuildAssets/create-octopuscli-linux-packages.sh

debian:bullseye only has libicu67

Add libicu67

---

source/Octopus.Cli/Commands/Releases/CreateReleaseCommand.cs

This change is to make the conversion from DB to VCS smoother for customers by avoiding the requirement to rewrite their build pipelines. The API itself still requires the gitref as provided by the portal and this change simply boils down to the cli tool setting the default.
Probably not what we would have built if we were creating this from scratch, but it simplifies the migration process and I could see us enforcing this a lot more once the initial adoption.

If gitRef is not provided, fall back to using the default branch

---

Dockerfiles/alpine/Dockerfile
Dockerfiles/nanoserver/Dockerfile
build/Build.cs
source/Octo.Tests/Commands/VersionTestFixture.cs
source/Octo.Tests/Octo.Tests.csproj
source/Octo/Octo.csproj
source/Octopus.Cli/Octopus.Cli.csproj
source/Octopus.DotNet.Cli/Octopus.DotNet.Cli.csproj

According to the [dotnet core support policy](https://dotnet.microsoft.com/platform/support/policy/dotnet-core):
- .Net Core 2.0 went EOL on October 1, 2018
- .Net Core 2.1 went EOL on  August 21, 2021
- .Net Core 2.2 went EOL on  December 23, 2019
- .Net Core 3.0 went EOL on  March 3, 2020
We will also need to modify the OctopusCLI [downloads page](https://octopus.com/downloads/octopuscli#netcore) (specifically [OctopusCLI.cshtml](https://github.com/OctopusDeploy/Octofront/blob/master/source/Octofront.Web.Public/Views/Downloads/OctopusCli/OctopusCli.cshtml) and [DownloadManager.cs](https://github.com/OctopusDeploy/Octofront/blob/master/source/Octofront.Core/Downloads/DownloadManager.cs#L136-L157)) to remove the `.NET Core 2.0` tab. 
Maybe we should replace it with guidance around using …

Drop netcore2.0 as it's EOL

---

.octopus/deployment_process.ocl
.octopus/schema-version.ocl
.octopus/schema_version.ocl

Slipway is the new place where we manage our releases - pulled out from octofront.
Looks like a migration happened as well - there's a bunch of change in there that's not mine...

Change release process to use slipway

---

source/Octopus.Cli/Commands/Releases/ReleasePlan.cs

Adjust the package reference name check to fix a missing edge case. The comparison should have been checked whether the passed value and the step reference value were both null/empty OR equal using a case-insensitive comparison.
Fixes #166

Fixed package reference name comparison in ReleasePlan

---

source/Octopus.Cli/CliProgram.cs

In summary, we let the OS mandate what TLS version is used, this given control to the system administrators.
Fixes https://github.com/OctopusDeploy/OctopusCLI/issues/170

Following advice from https://docs.microsoft.com/en-us/dotnet/api/System.Net.ServicePointManager.SecurityProtocol?view=net-6.0#remarks

---

source/Octo.Tests/Commands/ReleasePlanBuilderTests.cs
source/Octopus.Cli/Commands/Releases/ReleasePlanBuilder.cs

Fixes a bug where creating a release for config as code projects would fail when fetching packages, since IDs are now used again in the API instead of names.
Closes https://github.com/OctopusDeploy/Issues/issues/7660

Always use ID when fetching feeds

---

.github/workflows/build.yml
.octopus/deployment_process.ocl
.octopus/deployment_settings.ocl
.octopus/schema_version.ocl

This PR updates the pipeline to get the release notes that Release Please will have attached to the Release in GitHub and push them through to Octopus.

Updated the build pipeline to push release notes through to the Octopus website

---

.github/workflows/build.yml

We also included Docker images and the Linux distribution packages which are unnecessary to upload to the release

chore: Only calculate checksum and upload OSX/Linux/Win binary packages to release
